"""Add show_history_on_moderate to Patient

Revision ID: 85a758a13c28
Revises: a09cd03fabef
Create Date: 2026-09-09 08:29:17.936507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85a758a13c28'
down_revision: Union[str, Sequence[str], None] = 'a09cd03fabef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('show_history_on_moderate', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'show_history_on_moderate')
    # ### end Alembic commands ###
