"""Add location fields to Patient

Revision ID: a09cd03fabef
Revises: b2c3d4e5f6a7
Create Date: 2026-09-09 07:44:13.317856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a09cd03fabef'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('home_latitude', sa.String(), nullable=True))
    op.add_column('patients', sa.Column('home_longitude', sa.String(), nullable=True))
    op.add_column('patients', sa.Column('safe_radius_meters', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'safe_radius_meters')
    op.drop_column('patients', 'home_longitude')
    op.drop_column('patients', 'home_latitude')
    # ### end Alembic commands ###
